
CREATE VIEW [Base].[Companies]
AS
SELECT [recordID] [Id]
      , [UUID]
      , [Name]
      , [Description]
      , [Type]
      , [SubDomain]
      , [Parent]
      , [isDeleted]
      , [isActive]
      , [OrderVal]
      , [Icon]
      , [LargeIcon]
      , [ColourMain]
      , [ColourBG]
      , [ColourAlt]
      , [AddJob]
      , [ImitatingID]
      , [Ordering]
      , [ReportFooter1]
      , [ReportFooter2]
      , [ReportIcon]
      , [Frontpage]
      , [ReportCompanyLong]
      , [ReportCompanyShort]
      , [RecruitmentDomain]
      , [FriendlyDomain]
      , [DefaultLanguage]
      , [RootPath]
      , [URLAddress]
  FROM [iag].[dbo].[Companies]
