

CREATe VIEW [Base].[Users]
as
SELECT   [recordid] [Id]
      ,[UUID]
      ,[username]
      ,[firstname]
      ,[lastname]
      ,[email]
      ,[password]
      ,[password_expiry]
      ,[mobile]
      ,[seclevel]
      ,[type]
      ,[subtype]
      ,[isdeleted]
      ,[isactive]
      ,[datecreated]
      ,[datelastlogin]
      ,[notes]
      ,[company]
      ,[externalID]
      ,[Title]
      ,[IDNumber]
      ,[Age]
      ,[Race]
      ,[Country]
      ,[Province]
      ,[WorkEx]
      ,[HighestQualification]
      ,[EmployeeNumber]
      ,[MaritalStatus]
      ,[OverallHealth]
      ,[TandCsigned]
      ,[Gender]
      ,[isImage]
      ,[TandCsignedDate]
      ,[MiddleName]
      ,[PensionNumber]
      ,[DateOfBirth]
  FROM [iag].[dbo].[users]
