CREATE TABLE [dbo].[Companies] (
    [recordID]           INT            NOT NULL,
    [UUID]               NVARCHAR (200) CONSTRAINT [DF_Companies_UUID] DEFAULT (newid()) NULL,
    [Name]               NVARCHAR (200) NULL,
    [Description]        VARCHAR (500)  NULL,
    [Type]               INT            NULL,
    [SubDomain]          VARCHAR (100)  NULL,
    [Parent]             INT            NULL,
    [isDeleted]          INT            NULL,
    [isActive]           INT            NULL,
    [OrderVal]           INT            NULL,
    [Icon]               VARCHAR (150)  NULL,
    [LargeIcon]          IMAGE          NULL,
    [ColourMain]         VARCHAR (50)   NULL,
    [ColourBG]           VARCHAR (50)   NULL,
    [ColourAlt]          VARCHAR (50)   NULL,
    [AddJob]             INT            NULL,
    [ImitatingID]        INT            NULL,
    [Ordering]           VARCHAR (50)   NULL,
    [ReportFooter1]      NVARCHAR (250) NULL,
    [ReportFooter2]      NVARCHAR (250) NULL,
    [ReportIcon]         IMAGE          NULL,
    [Frontpage]          IMAGE          NULL,
    [ReportCompanyLong]  NVARCHAR (250) NULL,
    [ReportCompanyShort] NVARCHAR (250) NULL,
    [RecruitmentDomain]  VARCHAR (50)   NULL,
    [FriendlyDomain]     VARCHAR (200)  NULL,
    [DefaultLanguage]    INT            NULL,
    [RootPath]           VARCHAR (250)  NULL,
    [URLAddress]         VARCHAR (250)  NULL,
    CONSTRAINT [PK__Companie__D825197EEB4F1DBA] PRIMARY KEY CLUSTERED ([recordID] ASC)
);

