CREATE TABLE [dbo].[users] (
    [recordid]             INT            IDENTITY (1, 1) NOT NULL,
    [UUID]                 NVARCHAR (250) CONSTRAINT [DF_users_UUID] DEFAULT (newid()) NOT NULL,
    [username]             NVARCHAR (50)  NULL,
    [firstname]            NVARCHAR (150) NULL,
    [lastname]             NVARCHAR (150) NULL,
    [email]                NVARCHAR (355) NULL,
    [password]             NVARCHAR (150) NULL,
    [password_expiry]      DATETIME       NULL,
    [mobile]               VARCHAR (50)   NULL,
    [seclevel]             INT            NULL,
    [type]                 INT            CONSTRAINT [DF_users_type] DEFAULT ((0)) NULL,
    [subtype]              INT            NULL,
    [isdeleted]            INT            NULL,
    [isactive]             INT            NULL,
    [datecreated]          DATETIME       NULL,
    [datelastlogin]        DATETIME       NULL,
    [notes]                VARCHAR (8000) NULL,
    [company]              NVARCHAR (250) NULL,
    [externalID]           INT            NULL,
    [Title]                VARCHAR (50)   NULL,
    [IDNumber]             NVARCHAR (50)  NULL,
    [Age]                  VARCHAR (50)   NULL,
    [Race]                 NVARCHAR (150) NULL,
    [Country]              VARCHAR (500)  NULL,
    [Province]             VARCHAR (150)  NULL,
    [WorkEx]               VARCHAR (50)   NULL,
    [HighestQualification] VARCHAR (250)  NULL,
    [EmployeeNumber]       VARCHAR (50)   NULL,
    [MaritalStatus]        VARCHAR (50)   NULL,
    [OverallHealth]        VARCHAR (150)  NULL,
    [TandCsigned]          INT            CONSTRAINT [DF_users_TandCsigned] DEFAULT ((0)) NULL,
    [Gender]               VARCHAR (50)   NULL,
    [isImage]              INT            CONSTRAINT [DF_users_isImage] DEFAULT ((0)) NULL,
    [TandCsignedDate]      DATETIME       NULL,
    [MiddleName]           NVARCHAR (150) NULL,
    [PensionNumber]        NVARCHAR (50)  NULL,
    [DateOfBirth]          DATE           NULL,
    CONSTRAINT [PK__users__D82414B6FA5BAFDE] PRIMARY KEY CLUSTERED ([recordid] ASC)
);

