CREATE TABLE [Assess].[PersonalityResults] (
    [Id]                          BIGINT   IDENTITY (1, 1) NOT NULL,
    [AssessmentUsersid]           BIGINT   NOT NULL,
    [DateCompleted]               DATETIME CONSTRAINT [DF_PersonalityResults_DateCompleted] DEFAULT (getutcdate()) NOT NULL,
    [ConsistencyOfRankings]       INT      NULL,
    [RatingsAcquiescence]         INT      NULL,
    [GeneratingIdeas]             INT      NULL,
    [MakingDecisions]             INT      NULL,
    [DirectingPeople]             INT      NULL,
    [EmpoweringIndividuals]       INT      NULL,
    [ConvincingPeople]            INT      NULL,
    [ChallengingIdeas]            INT      NULL,
    [ArticulatingInformation]     INT      NULL,
    [ImpressingPeople]            INT      NULL,
    [InteractingWithPeople]       INT      NULL,
    [EstablishingRapport]         INT      NULL,
    [TeamWorking]                 INT      NULL,
    [ExploringPossibilities]      INT      NULL,
    [UnderstandingPeople]         INT      NULL,
    [ValuingIndividuals]          INT      NULL,
    [ResolvingConflict]           INT      NULL,
    [ConveyingSelfConfidence]     INT      NULL,
    [ShowingComposure]            INT      NULL,
    [InvitingFeedback]            INT      NULL,
    [ThinkingPositively]          INT      NULL,
    [EmbracingChange]             INT      NULL,
    [ManagingTasks]               INT      NULL,
    [UpholdingStandards]          INT      NULL,
    [DevelopingStrategies]        INT      NULL,
    [ProducingOutput]             INT      NULL,
    [TakingAction]                INT      NULL,
    [PursuingGoals]               INT      NULL,
    [SeizingOpportunities]        INT      NULL,
    [CheckingThings]              INT      NULL,
    [MeetingTimescales]           INT      NULL,
    [FollowingProcedures]         INT      NULL,
    [ProvidingInsights]           INT      NULL,
    [AdoptingPracticalApproaches] INT      NULL,
    [DevelopingExpertise]         INT      NULL,
    [ExaminingInformation]        INT      NULL,
    [DocumentingFacts]            INT      NULL,
    [InterpretingData]            INT      NULL,
    [CreatingInnovation]          INT      NULL,
    [StructuringTasks]            INT      NULL,
    [DrivingSuccess]              INT      NULL,
    [ProcessingDetails]           INT      NULL,
    [InvestigatingIssues]         INT      NULL,
    [EvaluatingProblems]          INT      NULL,
    [ProvidingLeadership]         INT      NULL,
    [CommunicatingInformation]    INT      NULL,
    [BuildingRelationships]       INT      NULL,
    [GivingSupport]               INT      NULL,
    [ShowingResilience]           INT      NULL,
    [AdjustingToChange]           INT      NULL,
    [isDeleted]                   INT      CONSTRAINT [DF_PersonalityResults_isDeleted] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_DataWavePersonalityResults] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_PersonalityResults_AssessmentUsers] FOREIGN KEY ([AssessmentUsersid]) REFERENCES [dbo].[AssessmentUsers] ([Id])
);

