
CREATE VIEW [dbo].[vwUsersCompanys] 
AS
SELECT  uc.[Id]
      , uc.[UUID]
      , uc.[Companyid]
      , c.[UUID] [CompanyUUID]
      , c.[Name] [Company]
      , uc.[Usersid]
      , u.[UUID] [UsersUUID]
      , u.[firstname] 
      , u.[lastname]
      , u.[IDNumber]
      , u.[email]
      , uc.[UsersidCreated]
      , uc.[DateCreated]
      , uc.[DateStarted]
      , uc.[EmployeeNo]
      , uc.[ContactNumber]
      , uc.[isEmployee]
      , uc.[isActive]
      , uc.[isDeleted]
  FROM [dbo].[UsersCompanys] uc
  INNER JOIN [dbo].[Companies] c ON c.[recordID] = uc.[Companyid] 
  INNER JOIN [dbo].[users] u ON u.[recordid] = uc.[Usersid] 
