

CREATE VIEW [Base].[vwEmployeesCorporateAccessLevels]
AS
SELECT [Id]
, [UUID]
, [Companyid]
, [CompanyUUID]
, [Usersid]
, [UserUUID]
, [FullName]
, [IDNumber]
, [EmployeeNumber]
, [EmployeeBusinessUnitTypesid]
, [EmployeeBusinessUnitTypeUUID]
, [EmployeeBusinessUnitType]
, [EmployeeBusinessUnitsid]
, [EmployeeBusinessUnitUUID]
, [EmployeeBusinessUnit]
, [EmployeeDepartmentsid]
, [EmployeeDepartmentUUID]
, [EmployeeDepartment]
, [isFullAccess]
, [isActive]
, [isDeleted]
FROM [Base].[base].[vwEmployeesCorporateAccessLevels]
