<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Utilities\fonts\Neo Sans Std Black Italic.otf" />
    <None Remove="Utilities\fonts\Neo Sans Std Black.otf" />
    <None Remove="Utilities\fonts\Neo Sans Std Bold Italic.otf" />
    <None Remove="Utilities\fonts\Neo Sans Std Bold.otf" />
    <None Remove="Utilities\fonts\Neo Sans Std Italic.otf" />
    <None Remove="Utilities\fonts\Neo Sans Std Light Italic.otf" />
    <None Remove="Utilities\fonts\Neo Sans Std Light.otf" />
    <None Remove="Utilities\fonts\Neo Sans Std Medium Italic.otf" />
    <None Remove="Utilities\fonts\Neo Sans Std Medium.otf" />
    <None Remove="Utilities\fonts\Neo Sans Std Regular.otf" />
    <None Remove="Utilities\fonts\Neo Sans Std Ultra Italic.otf" />
    <None Remove="Utilities\fonts\Neo Sans Std Ultra.otf" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Utilities\fonts\Neo Sans Std Black Italic.otf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Utilities\fonts\Neo Sans Std Black.otf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Utilities\fonts\Neo Sans Std Bold Italic.otf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Utilities\fonts\Neo Sans Std Bold.otf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Utilities\fonts\Neo Sans Std Italic.otf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Utilities\fonts\Neo Sans Std Light Italic.otf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Utilities\fonts\Neo Sans Std Light.otf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Utilities\fonts\Neo Sans Std Medium Italic.otf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Utilities\fonts\Neo Sans Std Medium.otf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Utilities\fonts\Neo Sans Std Regular.otf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Utilities\fonts\Neo Sans Std Ultra Italic.otf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Utilities\fonts\Neo Sans Std Ultra.otf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="QuestPDF" Version="2025.7.1" />
    <PackageReference Include="ServiceStack" Version="8.8.0" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="3.119.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Library.Database\Library.Database.csproj" />
    <ProjectReference Include="..\..\..\..\Library.Tools\Library.Tools.csproj" />
  </ItemGroup>

</Project>
