<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.7" />
    <PackageReference Include="QuestPDF" Version="2025.7.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Library.Database\Library.Database.csproj" />
    <ProjectReference Include="..\..\..\Library.Tools\Library.Tools.csproj" />
    <ProjectReference Include="..\Assess\Library.Assess\Library.Assess.csproj" />
  </ItemGroup>

</Project>
