<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <NoWarn>CS0168,CS1998,BL9993,CS0649,CS0436,0436</NoWarn>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="compilerconfig.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="compilerconfig.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="Radzen.Blazor" Version="*" />
    <PackageReference Include="System.Text.Encodings.Web" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\API\Microservices\Library\Library.Frog\Library.Frog.csproj" />
    <ProjectReference Include="..\Library.Database\Library.Database.csproj" />
    <ProjectReference Include="..\Library.Employee.SuccessionPlanning\Library.Employee.SuccessionPlanning.csproj" />
    <ProjectReference Include="..\Library.Security\Library.Security.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Components\Pages\Administration\SubPages\" />
  </ItemGroup>
</Project>