


CREATE VIEW [Goals].[vwContracts_Users]
AS
SELECT ROW_NUMBER() OVER(PARTITION BY c.[Companyid], c.[Usersid] ORDER BY c.[isDeleted] ASC, c.[isActive] DESC, c.[DateStart] DESC) [No]
      , c.[Id]
      , c.[UUID]
      , c.[Companyid]
      , cc.[UUID] [CompanyUUID]
      , cc.[Name] [Company]
      , c.[Usersid]
      , u.[UUID] [UsersUUID]
      , u.[Firstname]
      , u.[Lastname]
      , u.[IDNumber]
      , u.[Email] 
      , c.[ContractPeriodsid]
      , cp.[UUID] [ContractPeriodsUUID]
      , cp.[Name] [ContractPeriods]
      , cp.[DateStart] [ContractPeriodsDateStart]
      , cp.[DateEnd] [ContractPeriodsDateEnd]
      , cp.[Year] [ContractPeriodsYear]
      , c.[DateCreated]
      , c.[DateStart]
      , c.[DateEnd]
      , c.[isDepartmentTemplateSync]
      , c.[isIndividualTemplateSync]
      , c.[isActive]
      , c.[isDeleted]
  FROM [Goals].[Contracts] c
  INNER JOIN [Base].[Companies] cc ON cc.[recordID] = c.[Companyid] 
  INNER JOIN [Base].[Users] u ON u.[Id] = c.[Usersid] 
  INNER JOIN [Goals].[ContractPeriods] cp ON cp.[Id] = c.[ContractPeriodsid] 
